name: Input Demo

on: 
  workflow_dispatch:
    inputs: 
      lvls: 
        description: "Ange ett nivåvärde"
        required: true
        type: number

jobs: 
  run-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Kör om nivå är tillräcklig
        if: ${{ github.event.inputs.lvls >= 42 }}
        run: echo "Nivå är ${{ github.event.inputs.lvls }}, jobbet körs!"

      - name: Kör inte om nivå är för låg
        if: ${{ github.event.inputs.lvls < 42 }}
        run: echo "Nivå är ${{ github.event.inputs.lvls }}, kör ej jobbat, nivå under 42"
        

      
